{
 "title": "Amazon RDS - Performance Insights Dashboard",
 "description": "Amazon RDS - Performance Insights Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" }
  ]
 },
 "panels": [
  {
   "title": "Top Load Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Session Type",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "metricName": "session_type",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Top Users",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "metricName": "user",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Top Application",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "metricName": "application",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Top Host",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "metricName": "host",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Top Database",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "metricName": "name",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "Top SQL",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "metricName": "sql_tokenized",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "sharajag/PerfInsights-test-v4", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [
          { "property": { "name": "db.sql_tokenized.statement", "type": "string" }, "type": "groupBy" }
         ],
         "type": "and"
        },
        "limit": 10,
        "orderBy": { "name": "AVG", "type": "function" },
        "orderByDirection": "DESC",
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "sql_tokenized", "type": "functionParameter" }
         ],
         "type": "function"
        }
       },
       "sqlExpression": "SELECT AVG(sql_tokenized) FROM \"sharajag/PerfInsights-test-v4\" GROUP BY \"db.sql_tokenized.statement\" ORDER BY AVG() DESC LIMIT 10",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Top Wait event",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "metricName": "wait_event",
       "namespace": "sharajag/PerfInsights-test-v4",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    }
   ]
  },
  { "title": "Database load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Database load - SQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dimensions": {
      "db.sql_tokenized.statement": "*"
     },
     "metricName": "sql_tokenized",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database load - User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "metricName": "user",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "metricName": "name",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Wait event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dimensions": { "db.wait_event.name": "*" },
     "metricName": "wait_event",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Load - Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "metricName": "application",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Session Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "metricName": "session_type",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Load - Host",
   "type": "timeseries",
   "description": "Performance Insight metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "metricName": "host",
     "namespace": "sharajag/PerfInsights-test-v4",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}